name = "AutocorrelationShell"
uuid = "69d4c476-349e-11e9-22d5-d17d72ccee3f"
authors = ["Rishi Subramanian <risubramanian@ucdavis.edu>", "Shozen Dan <shodan@ucdavis.edu>", "Christina Chang"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
Plots = "1"
Reexport = "0.2, 1"
SpecialFunctions = "0.7 - 0.10"
Wavelets = "0.9"
julia = "1"
